const TEAM_TRANSLATIONS: Record<string, string> = {
  // Châu Á (AFC)
  'afghanistan': 'Afghanistan',
  'australia': 'Australia',
  'bahrain': 'Bahrain',
  'bangladesh': 'Bangladesh',
  'bhutan': 'Bhutan',
  'brunei': 'Brunei',
  'cambodia': 'Campuchia',
  'china': 'Trung Quốc',
  'guam': 'Guam',
  'hong kong': 'Hồng Kông',
  'india': 'Ấn Độ',
  'indonesia': 'Indonesia',
  'iran': 'Iran',
  'iraq': 'Iraq',
  'japan': 'Nhật Bản',
  'jordan': 'Jordan',
  'kazakhstan': 'Kazakhstan',
  'kuwait': 'Kuwait',
  'kyrgyzstan': 'Kyrgyzstan',
  'laos': 'Lào',
  'lebanon': 'Liban',
  'macau': 'Macao',
  'malaysia': 'Malaysia',
  'maldives': 'Maldives',
  'mongolia': 'Mông Cổ',
  'myanmar': 'Myanmar',
  'nepal': 'Nepal',
  'north korea': 'Triều Tiên',
  'korea dpr': 'Triều Tiên',
  'oman': 'Oman',
  'pakistan': 'Pakistan',
  'palestine': 'Palestine',
  'philippines': 'Philippines',
  'qatar': 'Qatar',
  'saudi arabia': 'Ả Rập Xê Út',
  'singapore': 'Singapore',
  'south korea': 'Hàn Quốc',
  'korea republic': 'Hàn Quốc',
  'korea': 'Hàn Quốc',
  'sri lanka': 'Sri Lanka',
  'syria': 'Syria',
  'taiwan': 'Đài Loan',
  'tajikistan': 'Tajikistan',
  'thailand': 'Thái Lan',
  'east timor': 'Đông Timor',
  'timor-leste': 'Đông Timor',
  'turkmenistan': 'Turkmenistan',
  'united arab emirates': 'UAE',
  'uae': 'UAE',
  'uzbekistan': 'Uzbekistan',
  'vietnam': 'Việt Nam',
  'yemen': 'Yemen',

  // Châu Âu (UEFA)
  'albania': 'Albania',
  'andorra': 'Andorra',
  'armenia': 'Armenia',
  'austria': 'Áo',
  'azerbaijan': 'Azerbaijan',
  'belarus': 'Belarus',
  'belgium': 'Bỉ',
  'bosnia and herzegovina': 'Bosnia & Herzegovina',
  'bosnia': 'Bosnia',
  'bulgaria': 'Bulgaria',
  'croatia': 'Croatia',
  'cyprus': 'Síp',
  'czech republic': 'Cộng hòa Séc',
  'czechia': 'Cộng hòa Séc',
  'denmark': 'Đan Mạch',
  'england': 'Anh',
  'estonia': 'Estonia',
  'faroe islands': 'Quần đảo Faroe',
  'finland': 'Phần Lan',
  'france': 'Pháp',
  'georgia': 'Georgia',
  'germany': 'Đức',
  'gibraltar': 'Gibraltar',
  'greece': 'Hy Lạp',
  'hungary': 'Hungary',
  'iceland': 'Iceland',
  'ireland': 'Ireland',
  'republic of ireland': 'Ireland',
  'israel': 'Israel',
  'italy': 'Ý',
  'kosovo': 'Kosovo',
  'latvia': 'Latvia',
  'liechtenstein': 'Liechtenstein',
  'lithuania': 'Lithuania',
  'luxembourg': 'Luxembourg',
  'malta': 'Malta',
  'moldova': 'Moldova',
  'monaco': 'Monaco',
  'montenegro': 'Montenegro',
  'netherlands': 'Hà Lan',
  'north macedonia': 'Bắc Macedonia',
  'macedonia': 'Bắc Macedonia',
  'northern ireland': 'Bắc Ireland',
  'norway': 'Na Uy',
  'poland': 'Ba Lan',
  'portugal': 'Bồ Đào Nha',
  'romania': 'Romania',
  'russia': 'Nga',
  'san marino': 'San Marino',
  'scotland': 'Scotland',
  'serbia': 'Serbia',
  'slovakia': 'Slovakia',
  'slovenia': 'Slovenia',
  'spain': 'Tây Ban Nha',
  'sweden': 'Thụy Điển',
  'switzerland': 'Thụy Sĩ',
  'turkey': 'Thổ Nhĩ Kỳ',
  'turkiye': 'Thổ Nhĩ Kỳ',
  'ukraine': 'Ukraine',
  'wales': 'Wales',

  // Nam Mỹ (CONMEBOL)
  'argentina': 'Argentina',
  'bolivia': 'Bolivia',
  'brazil': 'Brazil',
  'chile': 'Chile',
  'colombia': 'Colombia',
  'ecuador': 'Ecuador',
  'paraguay': 'Paraguay',
  'peru': 'Peru',
  'uruguay': 'Uruguay',
  'venezuela': 'Venezuela',

  // Bắc, Trung Mỹ & Caribe (CONCACAF)
  'canada': 'Canada',
  'costa rica': 'Costa Rica',
  'cuba': 'Cuba',
  'el salvador': 'El Salvador',
  'guatemala': 'Guatemala',
  'haiti': 'Haiti',
  'honduras': 'Honduras',
  'jamaica': 'Jamaica',
  'mexico': 'Mexico',
  'nicaragua': 'Nicaragua',
  'panama': 'Panama',
  'trinidad and tobago': 'Trinidad & Tobago',
  'united states': 'Mỹ',
  'usa': 'Mỹ',
  'us': 'Mỹ',

  // Châu Phi (CAF)
  'algeria': 'Algeria',
  'angola': 'Angola',
  'benin': 'Benin',
  'botswana': 'Botswana',
  'burkina faso': 'Burkina Faso',
  'burundi': 'Burundi',
  'cameroon': 'Cameroon',
  'cape verde': 'Cabo Verde',
  'central african republic': 'Cộng hòa Trung Phi',
  'chad': 'Chad',
  'comoros': 'Comoros',
  'congo': 'Congo',
  'dr congo': 'CHDC Congo',
  'djibouti': 'Djibouti',
  'egypt': 'Ai Cập',
  'equatorial guinea': 'Guinea Xích Đạo',
  'eritrea': 'Eritrea',
  'eswatini': 'Eswatini',
  'swaziland': 'Swaziland',
  'ethiopia': 'Ethiopia',
  'gabon': 'Gabon',
  'gambia': 'Gambia',
  'ghana': 'Ghana',
  'guinea': 'Guinea',
  'guinea-bissau': 'Guinea-Bissau',
  'ivory coast': 'Bờ Biển Ngà',
  'cote d\'ivoire': 'Bờ Biển Ngà',
  'kenya': 'Kenya',
  'lesotho': 'Lesotho',
  'liberia': 'Liberia',
  'libya': 'Libya',
  'madagascar': 'Madagascar',
  'malawi': 'Malawi',
  'mali': 'Mali',
  'mauritania': 'Mauritania',
  'mauritius': 'Mauritius',
  'morocco': 'Maroc',
  'mozambique': 'Mozambique',
  'namibia': 'Namibia',
  'niger': 'Niger',
  'nigeria': 'Nigeria',
  'rwanda': 'Rwanda',
  'sao tome and principe': 'São Tomé & Príncipe',
  'senegal': 'Senegal',
  'seychelles': 'Seychelles',
  'sierra leone': 'Sierra Leone',
  'somalia': 'Somalia',
  'south africa': 'Nam Phi',
  'south sudan': 'Nam Sudan',
  'sudan': 'Sudan',
  'tanzania': 'Tanzania',
  'togo': 'Togo',
  'tunisia': 'Tunisia',
  'uganda': 'Uganda',
  'zambia': 'Zambia',
  'zimbabwe': 'Zimbabwe',

  // Châu Đại Dương (OFC)
  'fiji': 'Fiji',
  'new caledonia': 'New Caledonia',
  'new zealand': 'New Zealand',
  'papua new guinea': 'Papua New Guinea',
  'samoa': 'Samoa',
  'solomon islands': 'Quần đảo Solomon',
  'tahiti': 'Tahiti',
  'tonga': 'Tonga',
  'vanuatu': 'Vanuatu',
};

/**
 * Translates an English team name (or stadium name/stage name if needed) into Vietnamese.
 * If no translation exists, returns the original name.
 */
export function translateTeamName(name: string): string {
  if (!name) return name;
  const cleanName = name.trim().toLowerCase();
  
  // Try to find direct translation
  if (TEAM_TRANSLATIONS[cleanName]) {
    return TEAM_TRANSLATIONS[cleanName];
  }

  // Handle placeholders like "Winner Group A", "Runner-up Group B"
  let translated = name;
  
  // Translate common tournament placeholders
  translated = translated.replace(/Winner Group\s+([A-H])/gi, 'Nhất bảng $1');
  translated = translated.replace(/Runner-up Group\s+([A-H])/gi, 'Nhì bảng $1');
  translated = translated.replace(/Winner match\s+(\d+)/gi, 'Thắng trận $1');
  translated = translated.replace(/Loser match\s+(\d+)/gi, 'Thua trận $1');

  return translated;
}
